Added option to take custom target name

diff --git a/createmf/createmf b/createmf/createmf
--- a/createmf/createmf
+++ b/createmf/createmf
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Author: Tyler Nguyen
-# Version: v1.0
+# Version: v1.3
 
 
 # :%s/^[ ]\+/\t/g : to indent correctly
@@ -13,7 +13,14 @@ Description: Create a template Makefile for your current project.
 	It saves a lot of time configuring a Makefile.
 	This can be used both in a small and large project
 
-Usage: createmf {filename}
+Usage: createmf [-o] {fileName} {executableName}
+Usage: createmf [-h]
+
+Options:
+  -h          open this manual
+  -o          give a custom target name
+
+Report bugs to tyler.t.nguyen@uconn.edu.
 EOF
 }
 
@@ -83,10 +90,25 @@ fi
 
 # ${filename#*.} : # removes everything before the first dot (inclusive) from left to right
 # ${filename%.*} : % removes everything after the first dot (inclusive) from right to left
+while getopts ":ho:" opt; do
+  case $opt in
+    h)  usage;
+        exit 0;
+        ;;
+    o)  shift;
+        ;;
+    \?) echo "Invalid option: $OPTARG" >&2;
+        exit 1;
+        ;;
+  esac
+done
 filename=$1
 extension="${filename#*.}"
-name="${filename%.*}"
-
+if [ -z "$2" ]; then
+  name="${filename%.*}"
+else
+  name=$2
+fi
 
 case $extension in
 	cs) COMPILER="mcs";
